name: SciComPy
channels:
  - conda-forge
  - defaults
dependencies:
  - autograd=1.2
  - cartopy=0.16.0
  - ipykernel=5.0.0
  - ipywidgets=7.4.2
  - matplotlib=3.0.0
  - networkx=2.2
  - numba=0.40.0
  - numpy=1.15.2
  - pandas=0.23.4
  - python=3.6.6
  - scikit-image=0.14.1
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - statsmodels=0.9.0
  - sympy=1.3
  - tensorflow=1.10.0
  - toolz=0.9.0
  - pip:
    - pyabc==0.9.2
