name: CompSciPy
channels:
  - conda-forge
  - defaults
dependencies:
  - autograd=1.2
  - cython=0.28.2
  - imageio=2.3.0
  - ipykernel=4.8.2
  - ipywidgets=7.2.1
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - keras=2.1.5
  - matplotlib=2.2.2
  - networkx=2.1
  - notebook=5.4.1
  - numba=0.38.0
  - numexpr=2.6.5
  - numpy=1.14.3
  - pandas=0.22.0
  - pillow=5.1.0
  - python=3.6.5
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - statsmodels=0.8.0
  - sympy=1.1.1
  - tensorflow=1.0.0
  - toolz=0.9.0
  - tqdm=4.23.3